apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call UPLOAD BINARY RW
on:
  workflow_dispatch:
jobs:
    call_rw:
      uses: mluzcabrera/reusableworkflowsrepo/.cloudbees/workflows/rw_upload_binary.yaml
      secrets: inherit
